# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cid', models.CharField(default='', max_length=64)),
                ('image', models.CharField(default='unknown', max_length=50)),
                ('tag', models.CharField(default='unknown', max_length=50)),
                ('memory', models.IntegerField(default=0)),
                ('ports', models.TextField(default='{}')),
                ('env', models.TextField(default='{}')),
                ('startOnReboot', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.Administrator')),
            ],
        ),
    ]
