# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-26 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containers',
            name='volumes',
            field=models.TextField(default='{}'),
        ),
    ]
