# Generated by Django 4.2.14 on 2025-08-28 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginSystem', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logFile', models.CharField(max_length=1000)),
                ('ipAddress', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=15)),
                ('jobSuccessSites', models.IntegerField()),
                ('jobFailedSites', models.IntegerField()),
                ('location', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destLoc', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DockerPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('CPUs', models.IntegerField()),
                ('Ram', models.IntegerField()),
                ('Bandwidth', models.TextField()),
                ('DiskSpace', models.TextField()),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('auth', models.TextField(default='Inactive', max_length=65532)),
                ('runTime', models.CharField(default='NEVER', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='NormalBackupDests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NormalBackupJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('config', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.normalbackupdests')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteBackupConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configtype', models.CharField(default='', max_length=255)),
                ('config', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteBackupSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=255)),
                ('timeintervel', models.CharField(max_length=200)),
                ('fileretention', models.CharField(max_length=200)),
                ('lastrun', models.CharField(max_length=200)),
                ('config', models.TextField()),
                ('RemoteBackupConfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.remotebackupconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('adminEmail', models.CharField(max_length=255)),
                ('phpSelection', models.CharField(max_length=10)),
                ('ssl', models.IntegerField()),
                ('state', models.IntegerField(default=1)),
                ('externalApp', models.CharField(default=None, max_length=30)),
                ('config', models.TextField(default='')),
                ('BackupLock', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loginSystem.administrator')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.package')),
            ],
        ),
        migrations.CreateModel(
            name='WPSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('path', models.CharField(default='', max_length=255)),
                ('FinalURL', models.CharField(default='', max_length=255)),
                ('AutoUpdates', models.CharField(default='Disabled', max_length=100)),
                ('PluginUpdates', models.CharField(default='Disabled', max_length=15)),
                ('ThemeUpdates', models.CharField(default='Disabled', max_length=15)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('WPLockState', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
        ),
        migrations.CreateModel(
            name='WPStaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.wpsites')),
                ('wpsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_wpsite', to='websiteFunctions.wpsites')),
            ],
        ),
        migrations.CreateModel(
            name='WPSitesBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WPSiteID', models.IntegerField(default=-1)),
                ('WebsiteID', models.IntegerField(default=-1)),
                ('config', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='wpplugins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=255)),
                ('config', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteBackupsites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WPsites', models.IntegerField(null=True)),
                ('database', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.remotebackupschedule')),
            ],
        ),
        migrations.CreateModel(
            name='PackageAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.dockerpackages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='NormalBackupSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.normalbackupjobs')),
            ],
        ),
        migrations.CreateModel(
            name='NormalBackupJobLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('message', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.normalbackupjobs')),
            ],
        ),
        migrations.CreateModel(
            name='GitLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.CharField(max_length=5)),
                ('message', models.TextField(max_length=65532)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
        ),
        migrations.CreateModel(
            name='GDriveSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.gdrive')),
            ],
        ),
        migrations.CreateModel(
            name='GDriveJobLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('message', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.gdrive')),
            ],
        ),
        migrations.CreateModel(
            name='DockerSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComposePath', models.TextField()),
                ('SitePath', models.TextField()),
                ('MySQLPath', models.TextField()),
                ('state', models.IntegerField(default=1)),
                ('SiteType', models.IntegerField(default=0)),
                ('MySQLDBName', models.CharField(max_length=100)),
                ('MySQLDBNUser', models.CharField(max_length=100)),
                ('CPUsMySQL', models.CharField(max_length=100)),
                ('MemoryMySQL', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('CPUsSite', models.CharField(max_length=100)),
                ('MemorySite', models.CharField(max_length=100)),
                ('SiteName', models.CharField(max_length=255, unique=True)),
                ('finalURL', models.TextField()),
                ('blogTitle', models.TextField()),
                ('adminUser', models.CharField(max_length=100)),
                ('adminEmail', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
        ),
        migrations.CreateModel(
            name='ChildDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, unique=True)),
                ('path', models.CharField(default=None, max_length=200)),
                ('ssl', models.IntegerField()),
                ('phpSelection', models.CharField(default=None, max_length=10)),
                ('alais', models.IntegerField(default=0)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
        ),
        migrations.CreateModel(
            name='Backupsv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('timeStamp', models.CharField(default='1756399647.7429814', max_length=255)),
                ('BasePath', models.TextField(default='')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
        ),
        migrations.CreateModel(
            name='BackupsLogsv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.CharField(default='1756399647.7435167', max_length=255)),
                ('message', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.backupsv2')),
            ],
        ),
        migrations.CreateModel(
            name='backupSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=15)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.dest')),
            ],
        ),
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
        ),
        migrations.CreateModel(
            name='BackupJobLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('message', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.backupjob')),
            ],
        ),
        migrations.CreateModel(
            name='aliasDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliasDomain', models.CharField(max_length=75)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
        ),
    ]
