# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aliasDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliasDomain', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='backupSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ChildDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, unique=True)),
                ('path', models.CharField(default=None, max_length=200)),
                ('ssl', models.IntegerField()),
                ('phpSelection', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='dest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destLoc', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, unique=True)),
                ('adminEmail', models.CharField(max_length=50)),
                ('phpSelection', models.CharField(max_length=10)),
                ('ssl', models.IntegerField()),
                ('state', models.IntegerField(default=1)),
                ('externalApp', models.CharField(default=None, max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loginSystem.Administrator')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.Package')),
            ],
        ),
        migrations.AddField(
            model_name='childdomains',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.Websites'),
        ),
        migrations.AddField(
            model_name='backupschedules',
            name='dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.dest'),
        ),
        migrations.AddField(
            model_name='backups',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.Websites'),
        ),
        migrations.AddField(
            model_name='aliasdomains',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.Websites'),
        ),
    ]
