mysql localhost {
    user = cyberpanel
    password = CYBERPANEL_DATABASE_PASSWORD
    dbname = cyberpanel
    port = 3306
}

sql_driver = mysql

passdb sql {
    query = SELECT email AS user, password FROM e_users WHERE email = '%{user}'
}

userdb sql {
    query = SELECT 5000 AS uid, 5000 AS gid, 'maildir' AS mail_driver, SUBSTRING(mail, 9) AS mail_path, CONCAT('/home/vmail/', SUBSTRING_INDEX(email, '@', -1), '/', SUBSTRING_INDEX(email, '@', 1)) AS home FROM e_users WHERE email = '%{user}'
}
