dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0

protocols {
    imap = yes
    pop3 = yes
    sieve = yes
}

log_timestamp = "%Y-%m-%d %H:%M:%S "

ssl = yes
ssl_server_cert_file = /etc/dovecot/cert.pem
ssl_server_key_file = /etc/dovecot/key.pem

namespace inbox {
    type = private
    separator = .
    prefix = INBOX.
    inbox = yes
}

mail_plugins {
    mail_compress = yes
}
mail_compress_write_method = gz
compress_gz_level = 6

service auth {
    unix_listener auth-master {
        mode = 0600
        user = vmail
    }

    unix_listener /var/spool/postfix/private/auth {
        mode = 0666
        user = postfix
        group = postfix
    }

    user = root
}

service auth-worker {
    user = root
}

protocol lda {
    log_path = /home/vmail/dovecot-deliver.log
    auth_socket_path = /var/run/dovecot/auth-master
    postmaster_address = postmaster@example.com
    lda_mailbox_autocreate = yes
    lda_mailbox_autosubscribe = yes

    mail_plugins {
        sieve = yes
    }
}

protocol pop3 {
    pop3_uidl_format = %{uid | hex(8)}%{uidvalidity | hex(8)}
}

auth_mechanisms = plain login
auth_master_user_separator = *

passdb master-passwd-file {
    driver = passwd-file
    master = yes
    passwd_file_path = /etc/dovecot/master-users
}

!include /etc/dovecot/dovecot-sql-2.4.conf

sieve_script personal {
    driver = file
    path = ~/sieve
    active_path = ~/.dovecot.sieve
}

service managesieve-login {
    inet_listener sieve {
        port = 4190
    }
}

service managesieve {
    process_limit = 256
}

protocol sieve {
}

service stats {
    unix_listener stats-reader {
        user = vmail
        group = vmail
        mode = 0660
    }
    unix_listener stats-writer {
        user = vmail
        group = vmail
        mode = 0660
    }
}
