# Generated by Django 3.1.3 on 2023-10-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteFunctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalPath', models.CharField(default=None, max_length=500)),
                ('fileName', models.CharField(default=None, max_length=200)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
        ),
    ]
