"""
Django settings for CyberCP project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
from django.utils.translation import gettext_lazy as _

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # dotenv not available, continue without it
    pass

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Resolve order: env var -> persistent key file -> generate once and persist.
# This removes the previously hard-coded (public) fallback key, which let anyone
# forge session/CSRF/password-reset tokens on installs that never set the env var.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    _secret_key_path = os.getenv('CYBERPANEL_SECRET_KEY_FILE', '/usr/local/CyberCP/secret_key')
    try:
        with open(_secret_key_path) as _skf:
            SECRET_KEY = _skf.read().strip()
    except OSError:
        SECRET_KEY = ''

    if not SECRET_KEY:
        import secrets as _secrets
        SECRET_KEY = _secrets.token_urlsafe(50)
        try:
            _fd = os.open(_secret_key_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
            with os.fdopen(_fd, 'w') as _skf:
                _skf.write(SECRET_KEY)
        except FileExistsError:
            # Another worker created it first; reuse that key so all workers agree.
            try:
                with open(_secret_key_path) as _skf:
                    SECRET_KEY = _skf.read().strip() or SECRET_KEY
            except OSError:
                pass
        except OSError:
            # Could not persist (e.g. permissions); use the in-memory key for now.
            pass

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Allow configuration via environment variable, with wildcard fallback for universal compatibility
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'baseTemplate',
    'firewall',
    'loginSystem',
    'packages',
    'websiteFunctions',
    'tuning',
    'serverStatus',
    'dns',
    'ftp',
    'userManagment',
    'databases',
    'mailServer',
    'serverLogs',
    'backup',
    'managePHP',
    'manageSSL',
    'api',
    'filemanager',
    'manageServices',
    'pluginHolder',
    'emailPremium',
    'emailMarketing',
    'cloudAPI',
    'highAvailability',
    's3Backups',
    'dockerManager',
    'containerization',
    'CLManager',
    'IncBackups',
    'aiScanner',
    'webmail',
    'emailDelivery',
    #    'WebTerminal'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'CyberCP.originDedupeMiddleware.OriginDedupeMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'CyberCP.secMiddleware.secMiddleware'
]

ROOT_URLCONF = 'CyberCP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'baseTemplate.context_processors.version_context',
                'baseTemplate.context_processors.cosmetic_context',
                'baseTemplate.context_processors.size_display_unit_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'CyberCP.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
# Prefer password from /etc/cyberpanel/mysqlPassword so panel stays in sync with CLI/install scripts.
_def_mysql_pass = ''
_def_mysql_root_pass = ''
try:
    _mysql_pass_file = '/etc/cyberpanel/mysqlPassword'
    if os.path.exists(_mysql_pass_file):
        with open(_mysql_pass_file, 'r') as _f:
            _def_mysql_pass = (_f.read() or '').strip()
            _def_mysql_root_pass = _def_mysql_pass
except Exception:
    pass

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'cyberpanel'),
        'USER': os.getenv('DB_USER', 'cyberpanel'),
        'PASSWORD': os.getenv('DB_PASSWORD', _def_mysql_pass),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    },
    'rootdb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('ROOT_DB_NAME', 'mysql'),
        'USER': os.getenv('ROOT_DB_USER', 'root'),
        'PASSWORD': os.getenv('ROOT_DB_PASSWORD', _def_mysql_root_pass or _def_mysql_pass),
        'HOST': os.getenv('ROOT_DB_HOST', 'localhost'),
        'PORT': os.getenv('ROOT_DB_PORT', '3306'),
    },
}
DATABASE_ROUTERS = ['backup.backupRouter.backupRouter']

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static/")
PUBLIC_ROOT = os.path.join(BASE_DIR, "public/")

STATIC_URL = '/static/'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LANGUAGES = (
    ('en', _('English')),
    ('cn', _('Chinese')),
    ('br', _('Bulgarian')),
    ('pt', _('Portuguese')),
    ('ja', _('Japanese')),
    ('bs', _('Bosnian')),
    ('gr', _('Greek')),
    ('ru', _('Russian')),
    ('tr', _('Turkish')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    ('pl', _('Polish')),
    ('vi', _('Vietnamese')),
    ('it', _('Italian')),
    ('de', _('Deutsch')),
    ('id', _('Indonesian')),
    ('bn', _('Bangla')),
    ('nb', _('Norwegian Bokmål')),
)

MEDIA_URL = '/usr/local/CyberCP/tmp/'
MEDIA_ROOT = MEDIA_URL
DATA_UPLOAD_MAX_MEMORY_SIZE = 2147483648

# Security settings
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Django 4.x sends Origin on HTTPS POSTs; without trusted origins CSRF returns 403 on login.
_csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
_csrf_origins_list = [o.strip() for o in _csrf_origins_env.split(',') if o.strip()]
_default_origins = [
    'https://84.247.184.182:8090',
    'http://84.247.184.182:8090',
    'https://127.0.0.1:8090',
    'http://127.0.0.1:8090',
    'https://vmi2387806.contaboserver.net:8090',
    'http://vmi2387806.contaboserver.net:8090',
]
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(_csrf_origins_list + _default_origins))
# Panel is served over HTTPS on :8090; secure cookies avoid stale CSRF/session mismatches.
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
_csrf_trusted_origins_file = '/etc/cyberpanel/csrf_trusted_origins'
if os.path.isfile(_csrf_trusted_origins_file):
    try:
        with open(_csrf_trusted_origins_file, 'r', encoding='utf-8', errors='replace') as _csrf_f:
            for _csrf_line in _csrf_f:
                _csrf_line = _csrf_line.strip()
                if _csrf_line and not _csrf_line.startswith('#'):
                    if _csrf_line not in CSRF_TRUSTED_ORIGINS:
                        CSRF_TRUSTED_ORIGINS.append(_csrf_line)
    except OSError:
        pass

# ---------------------------------------------------------------------------
# Plugin auto-sync: register on-disk plugins in INSTALLED_APPS
# ---------------------------------------------------------------------------
# External/optional plugins live either as installed marker dirs under
# /usr/local/CyberCP/<name>/ or as source packages under the plugin store
# roots below. A plugin is recognised when it ships both meta.xml and urls.py.
# Without this, plugin models raise:
#   "Model class <plugin>.models.X doesn't declare an explicit app_label and
#    isn't in an application in INSTALLED_APPS."
# Registering the app (not just including its URLs in pluginHolder) is what
# makes plugin models, admin and migrations work.
#
# Safety: a plugin is only registered when it is importable under its own
# directory name. If it ships an apps.py whose AppConfig `name` differs from
# the directory name, registering it would raise ImproperlyConfigured and take
# the whole panel down, so such plugins are skipped (they remain reachable via
# pluginHolder URL routing, which fails soft per-plugin).
import re as _re

_PLUGIN_SOURCE_ROOTS = ['/home/cyberpanel/plugins', '/home/cyberpanel-plugins']
# Core apps / reserved path segments that must never be auto-registered.
_PLUGIN_RESERVED_NAMES = frozenset(list(INSTALLED_APPS) + [
    'installed', 'help', 'api', 'static', 'public', 'plogical', 'CyberCP',
])
_PLUGIN_APPCONFIG_NAME_RE = _re.compile(r"""^\s*name\s*=\s*['"]([^'"]+)['"]""", _re.M)


def _plugin_dir_is_app(_dir):
    try:
        return (
            os.path.isdir(_dir)
            and os.path.exists(os.path.join(_dir, 'meta.xml'))
            and os.path.exists(os.path.join(_dir, 'urls.py'))
        )
    except (OSError, IOError):
        return False


def _plugin_appconfig_name_ok(_dir, _name):
    """True if the plugin has no apps.py, or its AppConfig.name == dir name."""
    _apps_py = os.path.join(_dir, 'apps.py')
    if not os.path.isfile(_apps_py):
        return True
    try:
        with open(_apps_py, 'r', encoding='utf-8', errors='replace') as _f:
            _txt = _f.read()
    except (OSError, IOError):
        return False
    _m = _PLUGIN_APPCONFIG_NAME_RE.search(_txt)
    if not _m:
        return True
    return _m.group(1) == _name


def _plugin_is_registrable(_name):
    """Locate a plugin dir for _name and decide if it is safe to register."""
    _cybercp_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for _root in [_cybercp_root] + _PLUGIN_SOURCE_ROOTS:
        _dir = os.path.join(_root, _name)
        if _plugin_dir_is_app(_dir):
            return _plugin_appconfig_name_ok(_dir, _name)
    return False


try:
    _cybercp_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    # Make plugin store roots importable so source-only plugins load.
    for _src_root in _PLUGIN_SOURCE_ROOTS:
        try:
            if os.path.isdir(_src_root) and _src_root not in sys.path:
                sys.path.append(_src_root)
        except (OSError, IOError):
            pass

    _existing_apps = set(INSTALLED_APPS)
    _candidate_names = set()
    for _root in [_cybercp_root] + _PLUGIN_SOURCE_ROOTS:
        if not os.path.isdir(_root):
            continue
        try:
            for _name in os.listdir(_root):
                if not _name.startswith('.'):
                    _candidate_names.add(_name)
        except (OSError, IOError):
            continue

    for _name in sorted(_candidate_names):
        if _name in _existing_apps or _name in _PLUGIN_RESERVED_NAMES:
            continue
        if _plugin_is_registrable(_name):
            INSTALLED_APPS.append(_name)
            _existing_apps.add(_name)
except (OSError, IOError):
    pass
