# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteFunctions', '0001_initial'),
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=1000)),
                ('totalEmails', models.IntegerField()),
                ('sent', models.IntegerField()),
                ('failed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=50, unique=True)),
                ('dateCreated', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='websiteFunctions.Websites')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailsInList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('firstName', models.CharField(default='', max_length=20)),
                ('lastName', models.CharField(default='', max_length=20)),
                ('verificationStatus', models.CharField(max_length=100)),
                ('dateCreated', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailMarketing.EmailLists')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=1000)),
                ('fromName', models.CharField(max_length=100)),
                ('fromEmail', models.CharField(max_length=150)),
                ('replyTo', models.CharField(max_length=150)),
                ('emailMessage', models.CharField(max_length=3000000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.Administrator')),
            ],
        ),
        migrations.CreateModel(
            name='SMTPHosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=150, unique=True)),
                ('port', models.CharField(max_length=10)),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.Administrator')),
            ],
        ),
        migrations.AddField(
            model_name='emailjobs',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailMarketing.EmailTemplate'),
        ),
    ]
