# Generated by Django 3.1.3 on 2023-10-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteFunctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuPers', models.CharField(max_length=10)),
                ('IO', models.CharField(max_length=10)),
                ('IOPS', models.CharField(max_length=10)),
                ('memory', models.CharField(max_length=10)),
                ('networkSpeed', models.CharField(max_length=10)),
                ('networkHexValue', models.CharField(max_length=10)),
                ('enforce', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
        ),
    ]
