# Generated by Django 4.2.14 on 2026-01-19 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('jail_name', models.CharField(max_length=100)),
                ('ban_reason', models.TextField(blank=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fail2ban_banned_ips',
                'ordering': ['-banned_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ban', 'IP Banned'), ('unban', 'IP Unbanned'), ('attack', 'Attack Detected'), ('whitelist', 'IP Whitelisted'), ('blacklist', 'IP Blacklisted')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('jail_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fail2ban_security_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fail2banSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('auto_ban_threshold', models.IntegerField(default=5)),
                ('ban_duration', models.IntegerField(default=3600)),
                ('whitelist_ips', models.TextField(blank=True, default='')),
                ('blacklist_ips', models.TextField(blank=True, default='')),
                ('enabled_jails', models.TextField(blank=True, default='sshd,openlitespeed,cyberpanel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fail2ban_settings',
            },
        ),
    ]
