from django.urls import path
from . import views

urlpatterns = [
    path('createBackup', views.create_backup, name='createBackupInc'),
    path('restoreRemoteBackups', views.restore_remote_backups, name='restoreRemoteBackupsInc'),
    path('backupDestinations', views.backup_destinations, name='backupDestinationsInc'),
    path('addDestination', views.add_destination, name='addDestinationInc'),
    path('populateCurrentRecords', views.populate_current_records, name='populateCurrentRecordsInc'),
    path('removeDestination', views.remove_destination, name='removeDestinationInc'),
    path('fetchCurrentBackups', views.fetch_current_backups, name='fetchCurrentBackupsInc'),
    path('submitBackupCreation', views.submit_backup_creation, name='submitBackupCreationInc'),
    path('getBackupStatus', views.get_backup_status, name='getBackupStatusInc'),
    path('deleteBackup', views.delete_backup, name='deleteBackupInc'),
    path('fetchRestorePoints', views.fetch_restore_points, name='fetchRestorePointsInc'),
    path('restorePoint', views.restore_point, name='restorePointInc'),
    path('scheduleBackups', views.schedule_backups, name='scheduleBackupsInc'),
    path('submitBackupSchedule', views.submit_backup_schedule, name='submitBackupScheduleInc'),
    path('scheduleDelete', views.schedule_delete, name='scheduleDeleteInc'),
    path('getCurrentBackupSchedules', views.get_current_backup_schedules, name='getCurrentBackupSchedulesInc'),
    path('fetchSites', views.fetch_sites, name='fetchSites'),
    path('saveChanges', views.save_changes, name='saveChanges'),
    path('removeSite', views.remove_site, name='removeSite'),
    path('addWebsite', views.add_website, name='addWebsite'),

    # V2 Backups URLs
    path('CreateV2Backup', views.CreateV2Backup, name='CreateV2Backup'),
    path('ConfigureV2Backup', views.ConfigureV2Backup, name='ConfigureV2Backup'),
    path('ConfigureV2BackupSetup', views.ConfigureV2BackupSetup, name='ConfigureV2BackupSetup'),
    path('RestoreV2backupSite', views.RestoreV2backupSite, name='RestoreV2backupSite'),
    path('selectwebsiteRetorev2', views.selectwebsiteRetorev2, name='selectwebsiteRetorev2'),
    path('selectreporestorev2', views.selectreporestorev2, name='selectreporestorev2'),
    path('RestorePathV2', views.RestorePathV2, name='RestorePathV2'),
    path('DeleteSnapshotV2Final', views.DeleteSnapshotV2Final, name='DeleteSnapshotV2Final'),
    path('CreateV2BackupButton', views.CreateV2BackupButton, name='CreateV2BackupButton'),
    path('selectwebsiteCreatev2', views.selectwebsiteCreatev2, name='selectwebsiteCreatev2'),
    path('CreateV2BackupStatus', views.CreateV2BackupStatus, name='CreateV2BackupStatus'),
    path('ConfigureSftpV2Backup', views.ConfigureSftpV2Backup, name='ConfigureSftpV2Backup'),

    path('schedulev2Backups', views.schedulev2Backups, name='schedulev2Backups'),
    path('DeleteScheduleV2', views.DeleteScheduleV2, name='DeleteScheduleV2'),
    path('CreateScheduleV2', views.CreateScheduleV2, name='CreateScheduleV2'),
    path('DeleteRepoV2', views.DeleteRepoV2, name='DeleteRepoV2'),
    path('DeleteV2BackupButton', views.DeleteV2BackupButton, name='DeleteV2BackupButton'),
]
