# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDNSStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverStatus', models.IntegerField(default=1)),
                ('type', models.CharField(default='NATIVE', max_length=6)),
                ('masterServer', models.CharField(default='', max_length=200)),
                ('masterIP', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SlaveServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slaveServer', models.CharField(default='NATIVE', max_length=200)),
                ('slaveServerIP', models.CharField(default='NATIVE', max_length=200)),
            ],
        ),
    ]
