# Generated by Django 4.2.14 on 2025-08-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this scheduled scan', max_length=200)),
                ('domains', models.TextField(help_text='JSON array of domains to scan')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='weekly', max_length=20)),
                ('scan_type', models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('custom', 'Custom Scan')], default='full', max_length=20)),
                ('time_of_day', models.TimeField(help_text='Time of day to run the scan (UTC)')),
                ('day_of_week', models.IntegerField(blank=True, help_text='Day of week for weekly scans (0=Monday, 6=Sunday)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly scans (1-31)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('notification_emails', models.TextField(blank=True, help_text='JSON array of email addresses')),
                ('notify_on_threats', models.BooleanField(default=True)),
                ('notify_on_completion', models.BooleanField(default=False)),
                ('notify_on_failure', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_scans', to='loginSystem.administrator')),
            ],
            options={
                'db_table': 'ai_scanner_scheduled_scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledScanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('domains_scanned', models.TextField(blank=True, help_text='JSON array of domains that were scanned')),
                ('total_scans', models.IntegerField(default=0)),
                ('successful_scans', models.IntegerField(default=0)),
                ('failed_scans', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('scan_ids', models.TextField(blank=True, help_text='JSON array of scan IDs created')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='aiScanner.scheduledscan')),
            ],
            options={
                'db_table': 'ai_scanner_scheduled_executions',
                'ordering': ['-execution_time'],
            },
        ),
        migrations.CreateModel(
            name='ScanStatusUpdate',
            fields=[
                ('scan_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('current_file', models.TextField(blank=True)),
                ('files_discovered', models.IntegerField(default=0)),
                ('files_scanned', models.IntegerField(default=0)),
                ('files_remaining', models.IntegerField(default=0)),
                ('threats_found', models.IntegerField(default=0)),
                ('critical_threats', models.IntegerField(default=0)),
                ('high_threats', models.IntegerField(default=0)),
                ('activity_description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_scanner_status_updates',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['scan_id', '-last_updated'], name='ai_scanner__scan_id_832121_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('scan_type', models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('custom', 'Custom Scan')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('files_scanned', models.IntegerField(default=0)),
                ('issues_found', models.IntegerField(default=0)),
                ('findings_json', models.TextField(blank=True, null=True)),
                ('summary_json', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='loginSystem.administrator')),
            ],
            options={
                'db_table': 'ai_scanner_history',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('wp_path', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='aiScanner.scanhistory')),
            ],
            options={
                'db_table': 'ai_scanner_file_tokens',
            },
        ),
        migrations.CreateModel(
            name='AIScannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('is_payment_configured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scanner_settings', to='loginSystem.administrator')),
            ],
            options={
                'db_table': 'ai_scanner_settings',
            },
        ),
    ]
