docRoot                   $VH_ROOT
vhDomain                  $VH_NAME
vhAliases                 *
adminEmails               root@localhost
enableGzip                1
enableIpGeo               1

errorlog $VH_ROOT/logs/error.log {
  useServer               0
  logLevel                DEBUG
  rollingSize             10M
}

accesslog $VH_ROOT/logs/access.log {
  useServer               0
  logFormat               "%h %l %u %t "%r" %>s %b "%{Referer}i" "%{User-Agent}i""
  logHeaders              5
  rollingSize             10M
  keepDays                30
  compressArchive         1
}

scripthandler  {
  add                     lsapi:cyberpanelphp php
}

extprocessor cyberpanelphp {
  type                    lsapi
  address                 UDS://tmp/lshttpd/cyberpanelphp.sock
  maxConns                10
  env                     LSAPI_CHILDREN=10
  initTimeout             60
  retryTimeout            0
  persistConn             1
  respBuffer              0
  autoStart               2
  path                    /usr/local/lsws/lsphp85/bin/lsphp
  extUser                 lscpd
  extGroup                lscpd
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           400
  procHardLimit           500
}

extprocessor cyberpanel {
  type                    proxy
  address                 127.0.0.1:5003
  maxConns                100
  pcKeepAliveTimeout      60
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

context /phpmyadmin/ {
  location                /usr/local/CyberCP/public/phpmyadmin/
  allowBrowse             1
  indexFiles              index.php
  addDefaultCharset       off
  scripthandler  {
    add                     lsapi:cyberpanelphp php
  }
}

context /snappymail/ {
  location                /usr/local/CyberCP/public/snappymail/
  allowBrowse             1
  indexFiles              index.php
  addDefaultCharset       off
  scripthandler  {
    add                     lsapi:cyberpanelphp php
  }
}

context /static/ {
  type                    null
  location                /usr/local/CyberCP/static/
  allowBrowse             1
}

context / {
  type                    proxy
  handler                 cyberpanel
  addDefaultCharset       off
}
