# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestCreateUser():
  def setup_method(self, method):
    self.driver = webdriver.Firefox(executable_path='/usr/bin/firefoxdriver')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createUser(self):
    self.driver.get("https://cyberpanel.xyz:8090/")
    self.driver.set_window_size(1366, 654)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("hello123")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Users").click()
    self.driver.find_element(By.CSS_SELECTOR, ".createNewUser span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1)").click()
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("Usman")
    self.driver.find_element(By.NAME, "lastName").send_keys("Nasir")
    self.driver.find_element(By.NAME, "email").send_keys("usman")
    self.driver.find_element(By.NAME, "email").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "email").send_keys("usman@cyberpersons.com")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) .form-control").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) .form-control")
    dropdown.find_element(By.XPATH, "//option[. = 'user']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-not-empty > option:nth-child(3)").click()
    self.driver.find_element(By.NAME, "websitesLimits").click()
    self.driver.find_element(By.NAME, "websitesLimits").send_keys("50")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(6) .form-control").send_keys("usman")
    self.driver.find_element(By.NAME, "password").send_keys("nasir")
    self.driver.find_element(By.CSS_SELECTOR, ".ng-empty").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(9) .form-control")
    dropdown.find_element(By.XPATH, "//option[. = 'HIGH']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ng-untouched > option:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-lg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alert-success").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".alert-success > p").text == "Account with username: usman is successfully created."
  

ct = TestCreateUser()
ct.setup_method('test')
ct.test_createUser()
ct.teardown_method('test')