# Generated by Django 4.2.14 on 2025-08-28 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteFunctions', '0001_initial'),
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=300)),
                ('frequency', models.CharField(max_length=50)),
                ('websiteData', models.IntegerField()),
                ('websiteDatabases', models.IntegerField()),
                ('websiteDataEmails', models.IntegerField()),
                ('retention', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IncJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
        ),
        migrations.CreateModel(
            name='OneClickBackups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=100)),
                ('months', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=300)),
                ('subscription', models.CharField(max_length=300, unique=True)),
                ('sftpUser', models.CharField(max_length=100)),
                ('config', models.TextField(default='{}')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('state', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loginSystem.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='JobSnapshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
                ('snapshotid', models.CharField(max_length=50)),
                ('destination', models.CharField(default='', max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IncBackups.incjob')),
            ],
        ),
        migrations.CreateModel(
            name='JobSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=300)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IncBackups.backupjob')),
            ],
        ),
    ]
