# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('proto', models.CharField(max_length=10)),
                ('port', models.CharField(max_length=25)),
                ('ipAddress', models.CharField(default=b'0.0.0.0/0', max_length=30)),
            ],
        ),
    ]
