# Generated by Django 3.1.3 on 2023-10-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('proto', models.CharField(max_length=10)),
                ('port', models.CharField(max_length=25)),
                ('ipAddress', models.CharField(default='0.0.0.0/0', max_length=30)),
            ],
        ),
    ]
