# Generated by Django 3.1.3 on 2023-10-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApachePHP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phpVers', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PHP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phpVers', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='installedPackagesApache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensionName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('phpVers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managePHP.apachephp')),
            ],
        ),
        migrations.CreateModel(
            name='installedPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extensionName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('phpVers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managePHP.php')),
            ],
        ),
    ]
