# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteFunctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column=b'ID', primary_key=True, serialize=False)),
                ('user', models.CharField(db_column=b'User', max_length=32, unique=True)),
                ('password', models.CharField(db_column=b'Password', max_length=64)),
                ('uid', models.IntegerField(db_column=b'Uid')),
                ('gid', models.IntegerField(db_column=b'Gid')),
                ('dir', models.CharField(db_column=b'Dir', max_length=255)),
                ('quotasize', models.IntegerField(db_column=b'QuotaSize')),
                ('status', models.CharField(db_column=b'Status', max_length=1)),
                ('ulbandwidth', models.IntegerField(db_column=b'ULBandwidth')),
                ('dlbandwidth', models.IntegerField(db_column=b'DLBandwidth')),
                ('date', models.DateField(db_column=b'Date')),
                ('lastmodif', models.CharField(db_column=b'LastModif', max_length=255)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.Websites')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
