# Generated by Django 3.1.3 on 2023-10-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteFunctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='User', max_length=32, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('uid', models.IntegerField(db_column='Uid')),
                ('gid', models.IntegerField(db_column='Gid')),
                ('dir', models.CharField(db_column='Dir', max_length=255)),
                ('quotasize', models.IntegerField(db_column='QuotaSize')),
                ('status', models.CharField(db_column='Status', max_length=1)),
                ('ulbandwidth', models.IntegerField(db_column='ULBandwidth')),
                ('dlbandwidth', models.IntegerField(db_column='DLBandwidth')),
                ('date', models.DateField(db_column='Date')),
                ('lastmodif', models.CharField(db_column='LastModif', max_length=255)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
