# Generated by Django 4.2.14 on 2026-06-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortManagerApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', max_length=64)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('scope', models.CharField(choices=[('read', 'read'), ('mutate', 'mutate')], default='read', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PortManagerAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, default='', max_length=128)),
                ('action', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
