# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-07 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteFunctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('domain', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('domainOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.Websites')),
            ],
            options={
                'db_table': 'e_domains',
            },
        ),
        migrations.CreateModel(
            name='EUsers',
            fields=[
                ('email', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('emailOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailServer.Domains')),
            ],
            options={
                'db_table': 'e_users',
            },
        ),
        migrations.CreateModel(
            name='Forwardings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('destination', models.TextField()),
            ],
            options={
                'db_table': 'e_forwardings',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128, unique=True)),
                ('transport', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'e_transport',
            },
        ),
    ]
